#!/usr/bin/env python3
"""Generate the three-weight eFootball selector font atlas."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts" / "efootball"
FONT_PATHS = (
    FONT_DIR / "eFootballSans-Light.ttf",
    FONT_DIR / "eFootballSans-Regular.ttf",
    FONT_DIR / "eFootballSans-Bold.ttf",
    FONT_DIR / "eFootballStencil-Regular.ttf",
)
OUTPUT_PATH = ROOT / "source" / "efootball_font_atlas.h"
GLYPHS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-+:&./'"
SCALE = 1
CELL_W = 40 * SCALE
CELL_H = 48 * SCALE
FONT_SIZE = 40 * SCALE
SIDE_MARGIN = 1 * SCALE


def main() -> None:
    fonts = tuple(ImageFont.truetype(str(path), FONT_SIZE) for path in FONT_PATHS)
    atlas = Image.new("L", (CELL_W * len(GLYPHS), CELL_H * len(fonts)), 0)
    draw = ImageDraw.Draw(atlas)
    advances: list[list[int]] = []

    for weight, font in enumerate(fonts):
        _, reference_top, _, reference_bottom = draw.textbbox((0, 0), "Ag", font=font)
        baseline_y = (
            weight * CELL_H
            + (CELL_H - (reference_bottom - reference_top)) // 2
            - reference_top
        )
        weight_advances: list[int] = []
        for index, glyph in enumerate(GLYPHS):
            left, _, _, _ = draw.textbbox((0, 0), glyph, font=font)
            x = index * CELL_W + SIDE_MARGIN - left
            draw.text((x, baseline_y), glyph, fill=255, font=font)
            weight_advances.append(max(1, min(255, round(font.getlength(glyph)))))
        advances.append(weight_advances)

    pixels = list(atlas.getdata())
    rows = []
    for offset in range(0, len(pixels), 24):
        rows.append("  " + ", ".join(str(value) for value in pixels[offset:offset + 24]))
    advance_rows = [
        "  {" + ", ".join(str(value) for value in values) + "}"
        for values in advances
    ]

    output = f'''/* Auto-generated by scripts/generate_efootball_font.py. */

#ifndef PES21_EFOOTBALL_FONT_ATLAS_H
#define PES21_EFOOTBALL_FONT_ATLAS_H

#include <stdint.h>

#define EFOOTBALL_FONT_CELL_W {CELL_W}
#define EFOOTBALL_FONT_CELL_H {CELL_H}
#define EFOOTBALL_FONT_GLYPHS "{GLYPHS}"
#define EFOOTBALL_FONT_COUNT ((int)(sizeof(EFOOTBALL_FONT_GLYPHS) - 1))
#define EFOOTBALL_FONT_COLS EFOOTBALL_FONT_COUNT
#define EFOOTBALL_FONT_WEIGHTS 4
#define EFOOTBALL_FONT_LIGHT 0
#define EFOOTBALL_FONT_REGULAR 1
#define EFOOTBALL_FONT_BOLD 2
#define EFOOTBALL_FONT_STENCIL 3
#define EFOOTBALL_FONT_ATLAS_W (EFOOTBALL_FONT_CELL_W * EFOOTBALL_FONT_COLS)
#define EFOOTBALL_FONT_ATLAS_H (EFOOTBALL_FONT_CELL_H * EFOOTBALL_FONT_WEIGHTS)

static const uint8_t
    efootball_font_advance[EFOOTBALL_FONT_WEIGHTS][EFOOTBALL_FONT_COUNT] = {{
{',\n'.join(advance_rows)}
}};

static const uint8_t
    efootball_font_atlas_alpha[EFOOTBALL_FONT_ATLAS_W * EFOOTBALL_FONT_ATLAS_H] = {{
{',\n'.join(rows)}
}};

static int efootball_font_glyph_index(char c) {{
  for (int i = 0; i < EFOOTBALL_FONT_COUNT; i++)
    if (EFOOTBALL_FONT_GLYPHS[i] == c)
      return i;
  return -1;
}}

#endif
'''
    OUTPUT_PATH.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
