#!/usr/bin/env python3
"""Build the overlay badge atlas from the generated Exhibition catalog."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from exhibition_team_catalog import load_catalog  # noqa: E402


HEADER_OUTPUT_PATH = ROOT / "source" / "badge_atlas.h"
BINARY_OUTPUT_PATH = ROOT / "data" / "badge_atlas.bin"
DEFAULT_CATALOG_PATH = ROOT / "data" / "exhibition_team_catalog.json"
DEFAULT_SYMBOL_ROOT = (
    ROOT / "local-debug" / "cpk-emblem-check" / "common" / "render" / "symbol"
)
DEFAULT_OVERRIDE_ROOT = ROOT / "assets" / "badges"

# 128px cells retain the native emblem detail used by the focused team card.
CELL = 128
COLS = 16


def badge_tile() -> Image.Image:
    return Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))


def fit_image(path: Path) -> Image.Image:
    with Image.open(path) as source:
        image = source.convert("RGBA")
    padding = CELL // 16
    image.thumbnail((CELL - padding, CELL - padding), Image.Resampling.LANCZOS)
    tile = badge_tile()
    tile.alpha_composite(
        image, ((CELL - image.width) // 2, (CELL - image.height) // 2)
    )
    return tile


def custom_team_image(override_root: Path, team_id: int) -> Path | None:
    candidates = (
        override_root / "teams" / f"{team_id}.png",
        override_root / f"team_{team_id}.png",
        override_root / f"{team_id}.png",
    )
    return next((path for path in candidates if path.is_file()), None)


def custom_category_image(
    override_root: Path, category_key: str, category_index: int
) -> Path | None:
    candidates = (
        override_root / "categories" / f"{category_key}.png",
        override_root / f"category_{category_key}.png",
        override_root / "categories" / f"{category_index}.png",
        override_root / f"category_{category_index}.png",
    )
    return next((path for path in candidates if path.is_file()), None)


def catalog_slot_count(catalog: dict[str, Any]) -> int:
    slots = [int(team["badge_slot"]) for team in catalog["teams"]]
    slots.extend(int(category["badge_slot"]) for category in catalog["categories"])
    if not slots:
        raise ValueError("team catalog contains no badge slots")
    if len(slots) != len(set(slots)):
        raise ValueError("team catalog contains duplicate badge slots")

    slot_count = max(slots) + 1
    if sorted(slots) != list(range(1, slot_count)):
        raise ValueError("team catalog badge slots must be contiguous after slot 0")
    declared_count = int(catalog.get("counts", {}).get("badge_slots", 0))
    if declared_count != slot_count:
        raise ValueError(
            f"team catalog declares {declared_count} slots, expected {slot_count}"
        )
    return slot_count


def catalog_badge_path(symbol_root: Path, relative_path: str) -> Path:
    source = (symbol_root / relative_path).resolve()
    try:
        source.relative_to(symbol_root)
    except ValueError as exc:
        raise ValueError(f"badge source escapes symbol root: {relative_path}") from exc
    if not source.is_file():
        raise FileNotFoundError(f"catalog badge source not found: {source}")
    return source


def paste_badge(atlas: Image.Image, slot: int, source: Path) -> None:
    atlas.paste(
        fit_image(source),
        ((slot % COLS) * CELL, (slot // COLS) * CELL),
    )


def emit_atlas(
    atlas: Image.Image,
    header_output_path: Path,
    binary_output_path: Path,
    slot_count: int,
    row_count: int,
    content_id: str,
) -> None:
    header_output_path.parent.mkdir(parents=True, exist_ok=True)
    binary_output_path.parent.mkdir(parents=True, exist_ok=True)
    binary_output_path.write_bytes(atlas.tobytes())
    header = f'''/* Auto-generated by scripts/generate_badge_atlas.py.
 * Catalog content ID: {content_id}
 */

#ifndef PES21_BADGE_ATLAS_H
#define PES21_BADGE_ATLAS_H

#include <stdint.h>

#define BADGE_ATLAS_CONTENT_ID "{content_id}"
#define BADGE_CELL_SIZE {CELL}
#define BADGE_ATLAS_COLS {COLS}
#define BADGE_ATLAS_SLOTS {slot_count}
#define BADGE_ATLAS_ROWS {row_count}
#define BADGE_ATLAS_W (BADGE_CELL_SIZE * BADGE_ATLAS_COLS)
#define BADGE_ATLAS_H (BADGE_CELL_SIZE * BADGE_ATLAS_ROWS)
#define BADGE_ATLAS_BYTES (BADGE_ATLAS_W * BADGE_ATLAS_H * 4u)

/* data/badge_atlas.bin is converted to this symbol by the devkitPro build. */
extern const uint8_t badge_atlas_bin[];
#define badge_atlas_rgba8 badge_atlas_bin

#endif
'''
    header_output_path.write_text(header, encoding="ascii", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--catalog",
        type=Path,
        default=DEFAULT_CATALOG_PATH,
        help="generated Exhibition team catalog",
    )
    parser.add_argument(
        "--symbol-root",
        type=Path,
        default=DEFAULT_SYMBOL_ROOT,
        help="extracted common/render/symbol directory from dt240_mobile_all.cpk",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=HEADER_OUTPUT_PATH,
        help="generated metadata C header path",
    )
    parser.add_argument(
        "--binary-output",
        type=Path,
        default=BINARY_OUTPUT_PATH,
        help="generated raw RGBA atlas path",
    )
    parser.add_argument(
        "--override-root",
        type=Path,
        default=DEFAULT_OVERRIDE_ROOT,
        help="optional HD PNG overrides",
    )
    args = parser.parse_args()

    catalog_path = args.catalog.resolve()
    symbol_root = args.symbol_root.resolve()
    override_root = args.override_root.resolve()
    if not symbol_root.is_dir():
        raise SystemExit(f"extracted symbol directory not found: {symbol_root}")

    catalog = load_catalog(catalog_path)
    slot_count = catalog_slot_count(catalog)
    row_count = (slot_count + COLS - 1) // COLS
    atlas = Image.new(
        "RGBA", (COLS * CELL, row_count * CELL), (0, 0, 0, 0)
    )

    # Slot 0 stays transparent; manifest slots are compact and independent of IDs.
    for team in catalog["teams"]:
        team_id = int(team["team_id"])
        source = custom_team_image(override_root, team_id)
        if source is None:
            source = catalog_badge_path(symbol_root, str(team["badge_source"]))
        paste_badge(atlas, int(team["badge_slot"]), source)

    for index, category in enumerate(catalog["categories"]):
        source = custom_category_image(
            override_root, str(category["key"]), index
        )
        if source is None:
            source = catalog_badge_path(
                symbol_root, str(category["badge_source"])
            )
        paste_badge(atlas, int(category["badge_slot"]), source)

    emit_atlas(
        atlas,
        args.output.resolve(),
        args.binary_output.resolve(),
        slot_count,
        row_count,
        str(catalog["content_id"]),
    )
    print(
        f"generated {args.output.resolve()} and {args.binary_output.resolve()} "
        f"({slot_count} slots, {COLS * CELL}x{row_count * CELL})"
    )


if __name__ == "__main__":
    main()
