#!/usr/bin/env python3
"""Build the overlay atlas from emblems extracted from dt240_mobile_all.cpk."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "source" / "badge_atlas.h"
DEFAULT_SYMBOL_ROOT = (
    ROOT / "local-debug" / "cpk-emblem-check" / "common" / "render" / "symbol"
)
CELL = 64
COLS = 16
CATEGORY_IMAGES = (
    "emblemLc/emb_0009.png",                  # English League
    "emblemLc/emb_0011.png",                  # Spanish League
    "emblemLc/emb_0012_b.png",                # Ligue 1
    "emblemLc/emb_0010.png",                  # Serie A
    "emblemLc/emb_0019.png",                  # Eredivisie
    "flag/e_000014_r.png",                    # German teams
    "other/emblemOther-clublEurope.png",       # Other Europe
    "other/emblemOther-clubLatinAmerica.png",  # South America clubs
    "other/emblemOther-nationalEurope.png",
    "other/emblemOther-nationalAfrica.png",
    "other/emblemOther-nationalNorthAmerica.png",
    "other/emblemOther-nationalLatinAmerica.png",
    "other/emblemOther-nationalAsia.png",
)
EXTRA_TEAM_IDS = (
    173,  # Manchester B
    177,  # Everton B
    179,  # Tottenham WB
    191,  # Benfica
    192,  # Porto
    193,  # Sporting CP
    234,  # Atalanta
    327,  # Napoli
    333,  # Torino
    377,  # Brighton WB
)
EXTRA_TEAM_SLOT_BASE = 140 + len(CATEGORY_IMAGES)
SLOTS = EXTRA_TEAM_SLOT_BASE + len(EXTRA_TEAM_IDS)
ROWS = (SLOTS + COLS - 1) // COLS


def badge_tile() -> Image.Image:
    return Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))


def fit_image(path: Path) -> Image.Image:
    image = Image.open(path).convert("RGBA")
    padding = CELL // 8
    image.thumbnail((CELL - padding, CELL - padding), Image.Resampling.LANCZOS)
    tile = badge_tile()
    tile.alpha_composite(
        image, ((CELL - image.width) // 2, (CELL - image.height) // 2)
    )
    return tile


def fallback_badge(slot: int) -> Image.Image:
    tile = badge_tile()
    draw = ImageDraw.Draw(tile)
    color = ((slot * 73) & 0xBF, 80 + ((slot * 47) & 0x7F), 150, 255)
    draw.ellipse(
        (CELL * 3 // 32, CELL * 3 // 32,
         CELL - CELL * 3 // 32 - 1, CELL - CELL * 3 // 32 - 1),
        fill=color,
        outline=(32, 48, 64, 255),
        width=max(1, CELL // 32),
    )
    inner = CELL * 10 // 32
    draw.ellipse(
        (inner, inner, CELL - inner - 1, CELL - inner - 1),
        fill=(245, 247, 250, 255),
    )
    return tile


def team_image(symbol_root: Path, team_id: int) -> Path | None:
    flag_root = symbol_root / "flag"
    candidates = (
        flag_root / f"e_{team_id:06d}_r_l.png",
        flag_root / f"e_{team_id:06d}_r.png",
        flag_root / f"e_{team_id:06d}_r_b.png",
        flag_root / f"e_{team_id:06d}_f_l.png",
        flag_root / f"e_{team_id:06d}_f.png",
        flag_root / f"e_{team_id:06d}_r_w.png",
        flag_root / f"flag_{team_id}.png",
    )
    return next((path for path in candidates if path.is_file()), None)


def large_variant(path: Path) -> Path:
    candidate = path.with_name(f"{path.stem}_l{path.suffix}")
    return candidate if candidate.is_file() else path


def emit_header(atlas: Image.Image, output_path: Path) -> None:
    values = [channel for pixel in atlas.getdata() for channel in pixel]
    lines = []
    for offset in range(0, len(values), 24):
        lines.append(
            "  " + ", ".join(str(value) for value in values[offset : offset + 24])
        )

    output = f'''/* Auto-generated by scripts/generate_badge_atlas.py. */

#ifndef PES21_BADGE_ATLAS_H
#define PES21_BADGE_ATLAS_H

#include <stdint.h>

#define BADGE_CELL_SIZE {CELL}
#define BADGE_ATLAS_COLS {COLS}
#define BADGE_ATLAS_SLOTS {SLOTS}
#define BADGE_ATLAS_ROWS {ROWS}
#define BADGE_ATLAS_W (BADGE_CELL_SIZE * BADGE_ATLAS_COLS)
#define BADGE_ATLAS_H (BADGE_CELL_SIZE * BADGE_ATLAS_ROWS)

static const uint8_t badge_atlas_rgba8[BADGE_ATLAS_W * BADGE_ATLAS_H * 4] = {{
{',\n'.join(lines)}
}};

#endif
'''
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--symbol-root",
        type=Path,
        default=DEFAULT_SYMBOL_ROOT,
        help="Extracted common/render/symbol directory from dt240_mobile_all.cpk",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="generated C header path",
    )
    args = parser.parse_args()
    symbol_root = args.symbol_root.resolve()
    if not symbol_root.is_dir():
        raise SystemExit(f"Extracted symbol directory not found: {symbol_root}")

    atlas = Image.new("RGBA", (COLS * CELL, ROWS * CELL), (0, 0, 0, 0))
    for team_id in range(140):
        source = team_image(symbol_root, team_id)
        badge = fit_image(source) if source else fallback_badge(team_id)
        atlas.paste(badge, ((team_id % COLS) * CELL, (team_id // COLS) * CELL))

    for index, relative_path in enumerate(CATEGORY_IMAGES):
        slot = 140 + index
        source = large_variant(symbol_root / relative_path)
        badge = fit_image(source) if source.is_file() else fallback_badge(slot)
        atlas.paste(badge, ((slot % COLS) * CELL, (slot // COLS) * CELL))

    # Custom selector rows keep their compact overlay slots while sourcing
    # the exact PES21 native emblem images for the migrated high team IDs.
    for index, team_id in enumerate(EXTRA_TEAM_IDS):
        slot = EXTRA_TEAM_SLOT_BASE + index
        source = team_image(symbol_root, team_id)
        badge = fit_image(source) if source else fallback_badge(slot)
        atlas.paste(badge, ((slot % COLS) * CELL, (slot // COLS) * CELL))

    emit_header(atlas, args.output.resolve())


if __name__ == "__main__":
    main()
