#!/usr/bin/env python3
"""Generate size-matched, supersampled eFootball font atlas rows."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts" / "efootball"
FONT_PATHS = (
    FONT_DIR / "eFootballSans-Light.ttf",
    FONT_DIR / "eFootballSans-Regular.ttf",
    FONT_DIR / "eFootballSans-Bold.ttf",
    FONT_DIR / "eFootballStencil-Regular.ttf",
)
OUTPUT_PATH = ROOT / "source" / "efootball_font_atlas.h"
GLYPHS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-+:&./'"
CELL_W = 40
CELL_H = 48
SUPERSAMPLE = 4
# The rows are grouped by font weight at each raster size. Keeping small
# copies near their display size avoids a 3:1 GL_LINEAR minification of text.
RASTERS = (
    ("", 40, 48),
    ("SMALL", 20, 24),
    ("TINY", 15, 18),
    ("MEDIUM", 30, 36),
)


def main() -> None:
    atlas = Image.new(
        "L", (CELL_W * len(GLYPHS), CELL_H * len(FONT_PATHS) * len(RASTERS)), 0
    )
    advances: list[list[list[int]]] = []
    for level, (_, width, height) in enumerate(RASTERS):
        level_advances: list[list[int]] = []
        for weight, path in enumerate(FONT_PATHS):
            font = ImageFont.truetype(str(path), width * SUPERSAMPLE)
            reference = Image.new("L", (1, 1))
            reference_draw = ImageDraw.Draw(reference)
            _, top, _, bottom = reference_draw.textbbox((0, 0), "Ag", font=font)
            baseline = (height * SUPERSAMPLE - (bottom - top)) // 2 - top
            weight_advances: list[int] = []
            for index, glyph in enumerate(GLYPHS):
                tile = Image.new(
                    "L", (width * SUPERSAMPLE, height * SUPERSAMPLE), 0
                )
                draw = ImageDraw.Draw(tile)
                left, _, _, _ = draw.textbbox((0, 0), glyph, font=font)
                draw.text(
                    (SUPERSAMPLE - left, baseline), glyph, fill=255, font=font
                )
                atlas.paste(
                    tile.resize((width, height), Image.Resampling.LANCZOS),
                    (index * CELL_W, (level * len(FONT_PATHS) + weight) * CELL_H),
                )
                weight_advances.append(
                    max(1, min(255, round(font.getlength(glyph) / SUPERSAMPLE)))
                )
            level_advances.append(weight_advances)
        advances.append(level_advances)

    pixels = list(atlas.getdata())
    rows = []
    for offset in range(0, len(pixels), 24):
        rows.append("  " + ", ".join(str(value) for value in pixels[offset:offset + 24]))
    def advance_rows(level: int) -> str:
        return ",\n".join(
            "  {" + ", ".join(str(value) for value in values) + "}"
            for values in advances[level]
        )

    output = f'''/* Auto-generated by scripts/generate_efootball_font.py. */

#ifndef PES21_EFOOTBALL_FONT_ATLAS_H
#define PES21_EFOOTBALL_FONT_ATLAS_H

#include <stdint.h>

#define EFOOTBALL_FONT_CELL_W {CELL_W}
#define EFOOTBALL_FONT_CELL_H {CELL_H}
#define EFOOTBALL_FONT_SMALL_CELL_W {RASTERS[1][1]}
#define EFOOTBALL_FONT_SMALL_CELL_H {RASTERS[1][2]}
#define EFOOTBALL_FONT_TINY_CELL_W {RASTERS[2][1]}
#define EFOOTBALL_FONT_TINY_CELL_H {RASTERS[2][2]}
#define EFOOTBALL_FONT_MEDIUM_CELL_W {RASTERS[3][1]}
#define EFOOTBALL_FONT_MEDIUM_CELL_H {RASTERS[3][2]}
#define EFOOTBALL_FONT_GLYPHS "{GLYPHS}"
#define EFOOTBALL_FONT_COUNT ((int)(sizeof(EFOOTBALL_FONT_GLYPHS) - 1))
#define EFOOTBALL_FONT_COLS EFOOTBALL_FONT_COUNT
#define EFOOTBALL_FONT_WEIGHTS 4
#define EFOOTBALL_FONT_RASTER_LEVELS {len(RASTERS)}
#define EFOOTBALL_FONT_LIGHT 0
#define EFOOTBALL_FONT_REGULAR 1
#define EFOOTBALL_FONT_BOLD 2
#define EFOOTBALL_FONT_STENCIL 3
#define EFOOTBALL_FONT_ATLAS_W (EFOOTBALL_FONT_CELL_W * EFOOTBALL_FONT_COLS)
#define EFOOTBALL_FONT_ATLAS_ROWS (EFOOTBALL_FONT_WEIGHTS * EFOOTBALL_FONT_RASTER_LEVELS)
#define EFOOTBALL_FONT_ATLAS_H (EFOOTBALL_FONT_CELL_H * EFOOTBALL_FONT_ATLAS_ROWS)

static const uint8_t
    efootball_font_advance[EFOOTBALL_FONT_WEIGHTS][EFOOTBALL_FONT_COUNT] = {{
{advance_rows(0)}
}};

static const uint8_t
    efootball_font_small_advance[EFOOTBALL_FONT_WEIGHTS][EFOOTBALL_FONT_COUNT] = {{
{advance_rows(1)}
}};

static const uint8_t
    efootball_font_tiny_advance[EFOOTBALL_FONT_WEIGHTS][EFOOTBALL_FONT_COUNT] = {{
{advance_rows(2)}
}};

static const uint8_t
    efootball_font_medium_advance[EFOOTBALL_FONT_WEIGHTS][EFOOTBALL_FONT_COUNT] = {{
{advance_rows(3)}
}};

static const uint8_t
    efootball_font_atlas_alpha[EFOOTBALL_FONT_ATLAS_W * EFOOTBALL_FONT_ATLAS_H] = {{
{',\n'.join(rows)}
}};

static int efootball_font_glyph_index(char c) {{
  for (int i = 0; i < EFOOTBALL_FONT_COUNT; i++)
    if (EFOOTBALL_FONT_GLYPHS[i] == c)
      return i;
  return -1;
}}

#endif
'''
    OUTPUT_PATH.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
