#!/usr/bin/env python3
"""Generate the compact RGBA-ready overlay font atlas header."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "assets" / "fonts" / "rajdhani" / "Rajdhani-SemiBold.ttf"
OUTPUT_PATH = ROOT / "source" / "font_atlas.h"
GLYPHS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-+:&./"
SCALE = 2
CELL_W = 16 * SCALE
CELL_H = 24 * SCALE
FONT_SIZE = 22 * SCALE
STROKE_WIDTH = 2


def main() -> None:
    font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)
    atlas = Image.new("L", (CELL_W * len(GLYPHS), CELL_H), 0)
    draw = ImageDraw.Draw(atlas)
    # Use one shared baseline for every glyph. Centering each glyph vertically
    # made lowercase text uneven and placed dots in the middle of URLs.
    _, reference_top, _, reference_bottom = draw.textbbox(
        (0, 0), "Ag", font=font, stroke_width=STROKE_WIDTH
    )
    baseline_y = (
        (CELL_H - (reference_bottom - reference_top)) // 2 - reference_top
    )

    for index, glyph in enumerate(GLYPHS):
        left, top, right, bottom = draw.textbbox(
            (0, 0), glyph, font=font, stroke_width=STROKE_WIDTH
        )
        width = right - left
        x = index * CELL_W + (CELL_W - width) // 2 - left
        draw.text(
            (x, baseline_y), glyph, fill=255, font=font,
            stroke_width=STROKE_WIDTH, stroke_fill=255
        )

    pixels = list(atlas.getdata())
    rows = []
    for offset in range(0, len(pixels), 24):
        rows.append("  " + ", ".join(str(value) for value in pixels[offset:offset + 24]))

    output = f'''/* Auto-generated by scripts/generate_overlay_font.py. */

#ifndef PES21_FONT_ATLAS_H
#define PES21_FONT_ATLAS_H

#include <stdint.h>

#define FONT_CELL_W {CELL_W}
#define FONT_CELL_H {CELL_H}
#define FONT_GLYPHS "{GLYPHS}"
#define FONT_COUNT ((int)(sizeof(FONT_GLYPHS) - 1))
#define FONT_COLS FONT_COUNT
#define FONT_ATLAS_W (FONT_CELL_W * FONT_COLS)
#define FONT_ATLAS_H FONT_CELL_H

static const uint8_t font_atlas_alpha[FONT_ATLAS_W * FONT_ATLAS_H] = {{
{',\n'.join(rows)}
}};

static int font_glyph_index(char c) {{
  for (int i = 0; i < FONT_COUNT; i++)
    if (FONT_GLYPHS[i] == c)
      return i;
  return -1;
}}

#endif
'''
    OUTPUT_PATH.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
