#!/usr/bin/env python3
"""Generate an anti-aliased luminance mask for team-rating stars."""

from math import cos, pi, sin
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "source" / "team_rating_star.h"
PREVIEW = ROOT / "art" / "team_rating_star.png"
SIZE = 128
SUPERSAMPLE = 8


def main() -> None:
    canvas_size = SIZE * SUPERSAMPLE
    image = Image.new("L", (canvas_size, canvas_size), 0)
    draw = ImageDraw.Draw(image)
    center = canvas_size * 0.5
    outer = canvas_size * 0.455
    inner = outer * 0.43
    points = []
    for point in range(10):
        angle = -pi * 0.5 + point * pi / 5.0
        radius = outer if point % 2 == 0 else inner
        points.append((center + cos(angle) * radius,
                       center + sin(angle) * radius))
    draw.polygon(points, fill=255)
    image = image.resize((SIZE, SIZE), Image.Resampling.LANCZOS)

    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    image.save(PREVIEW, optimize=True)
    pixels = list(image.getdata())
    lines = [
        "/* Generated by scripts/generate_team_rating_star.py. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define TEAM_RATING_STAR_W {SIZE}",
        f"#define TEAM_RATING_STAR_H {SIZE}",
        "",
        "static const uint8_t team_rating_star_luminance[",
        "    TEAM_RATING_STAR_W * TEAM_RATING_STAR_H] = {",
    ]
    for offset in range(0, len(pixels), 24):
        chunk = pixels[offset:offset + 24]
        lines.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.extend(["};", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"generated {OUTPUT} and {PREVIEW} ({SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
