#!/usr/bin/env python3
"""Generate the compact RGB565 team-select background embedded by overlay.c."""

from argparse import ArgumentParser
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "art" / "team_select_background.png"
DEFAULT_OUTPUT = ROOT / "source" / "team_select_background.h"
DEFAULT_PREVIEW = ROOT / "art" / "team_select_background_runtime.png"
WIDTH = 1280
HEIGHT = 720
PALETTE = ((11, 16, 181), (250, 255, 0))


def rgb565(red: int, green: int, blue: int) -> int:
    # GL_UNSIGNED_SHORT_5_6_5 consumes the native uint16_t value. Keep the
    # logical RGB bit order; swapping these bytes turns blue/ yellow into the
    # exact green/magenta pair seen on device.
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def nearest_palette_color(pixel: tuple[int, int, int]) -> tuple[int, int, int]:
    return min(
        PALETTE,
        key=lambda color: sum((channel - target) ** 2
                              for channel, target in zip(pixel, color)),
    )


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--preview", type=Path, default=DEFAULT_PREVIEW)
    parser.add_argument(
        "--preserve-colors",
        action="store_true",
        help="keep the source palette instead of snapping to blue/yellow",
    )
    args = parser.parse_args()

    source = Image.open(args.input).convert("RGB")
    fitted = ImageOps.fit(
        source,
        (WIDTH, HEIGHT),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )
    # The flat background uses an exact two-color palette. Preserve mode is
    # available for comparing richer generated concepts with the same runtime
    # texture path, UVs, and RGB565 packing.
    pixels = list(fitted.getdata())
    if not args.preserve_colors:
        pixels = [nearest_palette_color(pixel) for pixel in pixels]
    runtime_preview = Image.new("RGB", (WIDTH, HEIGHT))
    runtime_preview.putdata(pixels)
    args.preview.parent.mkdir(parents=True, exist_ok=True)
    runtime_preview.save(args.preview, optimize=True)
    values = [rgb565(red, green, blue) for red, green, blue in pixels]

    lines = [
        "/* Generated by scripts/generate_team_select_background.py. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define TEAM_SELECT_BG_W {WIDTH}",
        f"#define TEAM_SELECT_BG_H {HEIGHT}",
        "",
        "static const uint16_t team_select_background_rgb565[",
        "    TEAM_SELECT_BG_W * TEAM_SELECT_BG_H] = {",
    ]
    for offset in range(0, len(values), 16):
        chunk = values[offset : offset + 16]
        lines.append("  " + ", ".join(f"0x{value:04X}" for value in chunk) + ",")
    lines.extend(["};", ""])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(
        f"generated {args.output} ({WIDTH}x{HEIGHT}, "
        f"{len(values) * 2} RGB565 bytes, {len(set(values))} colors); "
        f"preview {args.preview}"
    )


if __name__ == "__main__":
    main()
