#!/usr/bin/env python3
"""Build playable League presets from a user's local FL26 installation.

Only competition IDs, names and eligible team IDs enter the public manifest.
Original emblem PNGs are exported solely to an explicitly selected ignored
local directory, never embedded in the repository or NRO.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from build_fl26_cup_catalog import (
    competition_keys, competition_members, decoded_member, index_cpk,
    select_logo, export_logos,
)


ROOT = Path(__file__).resolve().parents[1]

# FL26 competition ID, Switch selector category, visible name, source key.
LEAGUES = (
    (9, "english_league", "PREMIER LEAGUE", "ENGLAND_D1_LEAGUE"),
    (10, "serie_a", "SERIE A", "ITALY_D1_LEAGUE"),
    (11, "spanish_league", "LA LIGA", "SPAIN_D1_LEAGUE"),
    (12, "ligue_1", "LIGUE 1", "FRANCE_D1_LEAGUE"),
    (13, "eredivisie", "EREDIVISIE", "NETHERLANDS_D1_LEAGUE"),
    (14, "liga_portugal", "LIGA PORTUGAL", "PORTUGAL_D1_LEAGUE"),
    (39, "german_teams", "BUNDESLIGA", "GERMANY_D1_LEAGUE"),
    (21, "brazil_serie_a", "BRASILEIRAO SERIE A", "BRAZIL_D1_LEAGUE"),
    (41, "j1_league", "J1 LEAGUE", "JAPAN_D1_LEAGUE"),
    (119, "turkish_league", "TURKISH SUPER LIG", "TURKEY_D1_LEAGUE"),
    (66, "english_second", "ENGLISH CHAMPIONSHIP", "ENGLAND_D2_LEAGUE"),
    (67, "spanish_second", "SPANISH 2ND DIV", "SPAIN_D2_LEAGUE"),
    (68, "ligue_2", "LIGUE 2", "FRANCE_D2_LEAGUE"),
)


def build_manifest(root: Path, catalog_path: Path) -> dict:
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    categories = {row["key"]: (index, row)
                  for index, row in enumerate(catalog["categories"])}
    season = root / "download/data_s2526.cpk"
    latest = root / "download/data_s2526c.cpk"
    symbol = root / "Data/dt15_x64.cpk"
    si, sb = index_cpk(season)
    li, lb = index_cpk(latest)
    symbols, _ = index_cpk(symbol)
    competition_raw = decoded_member(
        season, si, sb, "common/etc/pesdb/Competition.bin")
    entry_raw = decoded_member(
        latest, li, lb, "common/etc/pesdb/CompetitionEntry.bin")
    names = competition_keys(competition_raw)
    members = competition_members(entry_raw)
    leagues = []
    for comp_id, key, label, expected_name in LEAGUES:
        if names.get(comp_id) != expected_name:
            raise ValueError(f"FL26 competition {comp_id}: {names.get(comp_id)}")
        if key not in categories:
            continue  # Retired selector category; never expose its league.
        category_index, category = categories[key]
        eligible = set(int(team) for team in category["team_ids"])
        pool = [team for team in members.get(comp_id, []) if team in eligible]
        if len(pool) < 8:
            # A league badge must not front a tiny subset (notably the base
            # checkout's two playable Bundesliga clubs). Regenerate after the
            # staged 18-club selector has been validated and promoted.
            continue
        if len(pool) > 32:
            raise ValueError(f"League {comp_id} exceeds 32 playable teams")
        leagues.append({
            "competition_id": comp_id,
            "name": label,
            "category_key": key,
            "category_index": category_index,
            "team_ids": pool,
            "logo_file": select_logo(comp_id, symbols),
        })
    leagues.append({
        "competition_id": 0,
        "name": "FOOTBALLNX LEAGUE",
        "category_key": None,
        "category_index": 255,
        "team_ids": [],
        "logo_file": None,
    })
    return {
        "schema_version": 1,
        "source": "local SP Football Life 2026 Competition.bin, CompetitionEntry.bin and dt15_x64.cpk",
        "competition_sha256": hashlib.sha256(competition_raw).hexdigest(),
        "entry_sha256": hashlib.sha256(entry_raw).hexdigest(),
        "catalog_content_id": catalog["content_id"],
        "leagues": leagues,
    }


def render_header(manifest: dict) -> str:
    lines = [
        "/* Generated by tools/build_fl26_league_catalog.py; do not edit. */",
        "#ifndef PES21_FL26_LEAGUE_CATALOG_GENERATED_H",
        "#define PES21_FL26_LEAGUE_CATALOG_GENERATED_H",
        "#include <stdint.h>",
        "typedef struct {",
        "  uint16_t competition_id;",
        "  uint8_t category_index;",
        "  uint8_t default_team_count;",
        "  const char *name;",
        "  const char *logo_file;",
        "  const uint32_t *team_ids;",
        "  uint32_t pool_count;",
        "} Fl26LeagueCatalogEntry;",
    ]
    for index, league in enumerate(manifest["leagues"][:-1]):
        teams = ", ".join(f"{team}u" for team in league["team_ids"])
        lines.append(f"static const uint32_t fl26_league_pool_{index}[] = {{{teams}}};")
    lines.append("static const Fl26LeagueCatalogEntry fl26_league_catalog[] = {")
    for index, league in enumerate(manifest["leagues"][:-1]):
        lines.append(
            f'  {{{league["competition_id"]}u, {league["category_index"]}u, '
            f'{len(league["team_ids"])}u, "{league["name"]}", '
            f'"{league["logo_file"]}", fl26_league_pool_{index}, '
            f'{len(league["team_ids"])}u}},'
        )
    lines.append('  {0u, 255u, 16u, "FOOTBALLNX LEAGUE", 0, 0, 0u},')
    lines.extend((
        "};",
        f'#define FL26_LEAGUE_CUSTOM_INDEX {len(manifest["leagues"]) - 1}u',
        "#define FL26_LEAGUE_CATALOG_COUNT ((uint32_t)(sizeof(fl26_league_catalog) / sizeof(fl26_league_catalog[0])))",
        "#endif",
        "",
    ))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fl26-root", type=Path,
                        default=Path("D:/Games/SP Football Life 2026"))
    parser.add_argument("--catalog", type=Path,
                        default=ROOT / "data/exhibition_team_catalog_migration.json")
    parser.add_argument("--manifest-output", type=Path,
                        default=ROOT / "data/fl26_league_catalog.json")
    parser.add_argument("--header-output", type=Path,
                        default=ROOT / "source/fl26_league_catalog_generated.h")
    parser.add_argument("--logo-output", type=Path,
                        help="ignored local LeagueLogos directory")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = build_manifest(args.fl26_root, args.catalog)
    manifest = json.dumps(result, indent=2, ensure_ascii=True) + "\n"
    header = render_header(result)
    if args.check:
        if (args.manifest_output.read_text(encoding="utf-8") != manifest or
                args.header_output.read_text(encoding="utf-8") != header):
            raise SystemExit("FL26 League catalog is out of date")
    else:
        args.manifest_output.write_text(manifest, encoding="utf-8")
        args.header_output.write_text(header, encoding="utf-8")
    if args.logo_output:
        # The Cup helper only needs a sequence of logo_file fields. Its
        # original bytes are kept in this ignored local destination.
        export_logos(args.fl26_root, result["leagues"], args.logo_output)
    print(json.dumps({"leagues": len(result["leagues"]),
                      "custom_index": len(result["leagues"]) - 1,
                      "catalog_content_id": result["catalog_content_id"]}))


if __name__ == "__main__":
    main()
