"""Build the compact, public roster pool used by simulated League fixtures.

Only the committed PESDB identity registry is read. BaseId is retained as the
cross-update player identity; native storage IDs are deliberately not used.
"""

from __future__ import annotations

import hashlib
import json
import unicodedata
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "pes21_player_registry.json"
TARGET = ROOT / "source" / "league_scorer_pool_generated.inc"
PLAYERS_PER_TEAM = 16


def ascii_name(value: str) -> str:
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    return " ".join(value.split())[:47]


def stable_order(team: int, player: dict) -> bytes:
    return hashlib.sha256(f"{team}:{player['ef_base_id']}".encode()).digest()


def main() -> None:
    registry = json.loads(SOURCE.read_text(encoding="utf-8"))
    teams: dict[int, list[dict]] = defaultdict(list)
    for player in registry["players"]:
        if player.get("status") != "active" or not player.get("ef_base_id"):
            continue
        for team in player.get("team_ids", []):
            teams[int(team)].append(player)

    lines = [
        "// Generated by tools/generate_league_scorer_pool.py from the public PESDB registry.",
        "// Simulated scorers use eFootball BaseId, never native storage IDs.",
        "// Do not edit manually.",
        "typedef struct { uint32_t team, first, count; } LeagueScorerPoolTeam;",
        "typedef struct { uint32_t base_id, portrait_id; const char *name; } LeagueScorerPoolPlayer;",
        "static const LeagueScorerPoolTeam league_scorer_pool_teams[] = {",
    ]
    pool: list[dict] = []
    for team in sorted(teams):
        roster = sorted(teams[team], key=lambda p: stable_order(team, p))
        # Prefer players with authored faces, but retain some newer players
        # without one so a team is not restricted to its legacy stars.
        faced = [p for p in roster if p.get("face_owner_id") is not None][:8]
        others = [p for p in roster if p not in faced][:8]
        chosen = sorted(faced + others, key=lambda p: stable_order(team, p))
        lines.append(f"  {{{team}u, {len(pool)}u, {len(chosen)}u}},")
        pool.extend(chosen)
    lines += ["};", "static const LeagueScorerPoolPlayer league_scorer_pool_players[] = {"]
    for player in pool:
        name = ascii_name(player.get("canonical_name", "")) or "PLAYER"
        name = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f"  {{{int(player['ef_base_id'])}u, "
            f"{int(player.get('portrait_asset_id') or 0)}u, \"{name}\"}},"
        )
    lines += [
        "};",
        "typedef struct { uint32_t portrait_id, base_id; } LeagueScorerIdentity;",
        "static const LeagueScorerIdentity league_scorer_identities[] = {",
    ]
    for player in sorted(registry["players"],
                         key=lambda p: int(p.get("portrait_asset_id") or 0)):
        portrait_id = int(player.get("portrait_asset_id") or 0)
        if portrait_id and player.get("ef_base_id"):
            lines.append(
                f"  {{{portrait_id}u, {int(player['ef_base_id'])}u}},"
            )
    lines += ["};", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(teams)} teams, {len(pool)} players -> {TARGET}")


if __name__ == "__main__":
    main()
