#!/usr/bin/env python3
"""Generate the NRO roster/build-ID include from the paired native CPK.

The existing eFootball rating overrides are preserved; new FL26-only players
fall back to their native Player.bin stats rather than a fabricated rating.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from build_fl26_cup_catalog import decoded_member, index_cpk
from pesdb import parse_pes21_assignments, parse_player_ids


ROOT = Path(__file__).resolve().parents[1]


def rating_block(source: str) -> str:
    marker = ("static const ExhibitionMigrationPlayerRating "
              "exhibition_player_migration_canary_ratings[] = {")
    start = source.find(marker)
    if start < 0:
        raise ValueError("existing migration rating array is missing")
    end = source.find("};", start)
    if end < 0:
        raise ValueError("existing migration rating array is unterminated")
    block = source[start:end + 2]
    ids = [int(value) for value in re.findall(r"\{(\d+)u,", block)]
    if ids != sorted(set(ids)) or len(ids) < 10_000:
        raise ValueError("existing eFootball ratings are unsorted or incomplete")
    return block


def make_include(catalog: dict, assignment_data: bytes,
                 player_data: bytes, build_id: str, existing_ratings: str,
                 *, expected_teams: int = 459) -> str:
    if not re.fullmatch(r"[0-9a-f]{16}", build_id):
        raise ValueError("loose CPK build ID is not a 16-digit content ID")
    assignments = parse_pes21_assignments(assignment_data)
    players = parse_player_ids(player_data, "pes21")
    rows = sorted(catalog["teams"], key=lambda row: int(row["team_id"]))
    if expected_teams < 1 or len(rows) != expected_teams or len({int(row["team_id"]) for row in rows}) != expected_teams:
        raise ValueError(f"selector does not contain {expected_teams} unique teams")
    lines = [
        "// Generated by tools/stage_fl26_migration_roster_include.py.",
        f"// Paired loose CPK build ID: {build_id}",
        "// Local candidate only; do not commit extracted roster data.",
        "",
        f'#define PES21_PLAYER_MIGRATION_BUILD_ID "{build_id}"',
        "",
    ]
    for team in rows:
        logical = int(team["team_id"])
        physical = int(team["physical_team_id"])
        roster = assignments.get(physical, [])
        if not 18 <= len(roster) <= 40:
            raise ValueError(f"team {logical}/{physical} has {len(roster)} players")
        player_ids = [int(row.player_id) for row in roster]
        if len(set(player_ids)) != len(player_ids) or not set(player_ids) <= players:
            raise ValueError(f"team {logical} has duplicate/missing native players")
        shirts = [int(row.shirt) & 0xFF for row in roster]
        lines.append(
            f"static const uint32_t exhibition_migration_team_{logical}_players[] = {{")
        for start in range(0, len(player_ids), 8):
            lines.append("    " + " ".join(
                f"{value}u," for value in player_ids[start:start + 8]))
        lines.extend(["};",
                      f"static const uint8_t exhibition_migration_team_{logical}_shirts[] = {{"])
        for start in range(0, len(shirts), 12):
            lines.append("    " + " ".join(
                f"{value}," for value in shirts[start:start + 12]))
        lines.extend(["};", ""])
    lines.extend([existing_ratings, "",
                  "static const ExhibitionMasterRoster "
                  "exhibition_player_migration_canary_rosters[] = {"])
    for team in rows:
        logical = int(team["team_id"])
        lines.extend([
            "    {",
            f"        {logical}u,",
            f"        exhibition_migration_team_{logical}_players,",
            f"        exhibition_migration_team_{logical}_shirts,",
            f"        sizeof(exhibition_migration_team_{logical}_players) /",
            f"            sizeof(exhibition_migration_team_{logical}_players[0]),",
            "    },",
        ])
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidate", type=Path,
                        default=ROOT / "local-debug/fl26-bundesliga-indonesia-paired-v2")
    parser.add_argument("--selector", type=Path,
                        default=ROOT / "local-debug/fl26-bundesliga-indonesia-selector-v2")
    parser.add_argument("--ratings-include", type=Path,
                        default=ROOT / "source/exhibition_rosters_migration_canary_generated.inc")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "local-debug/fl26-bundesliga-indonesia-selector-v2/exhibition_rosters_migration_canary_generated.inc")
    args = parser.parse_args()
    output = args.output.resolve()
    if (ROOT / "local-debug").resolve() not in output.parents:
        raise ValueError("generated roster include must stay in local-debug")
    report = json.loads((args.candidate / "paired-report.json").read_text(
        encoding="utf-8"))
    catalog = json.loads((args.selector / "exhibition_team_catalog_migration.json")
                         .read_text(encoding="utf-8"))
    if report["loose_build_id"] != catalog["content_id"]:
        raise ValueError("selector and CPK build IDs differ")
    archive = args.candidate / "LooseCpk/dt200_mobile_all.cpk"
    index, base = index_cpk(archive)
    def member(name: str) -> bytes:
        return decoded_member(archive, index, base,
                              f"common/etc/pesdb/{name}")
    text = make_include(
        catalog, member("PlayerAssignment.bin"), member("Player.bin"),
        report["loose_build_id"],
        rating_block(args.ratings_include.read_text(encoding="utf-8")),
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(json.dumps({"output": str(output), "build_id": report["loose_build_id"],
                      "rosters": len(catalog["teams"]), "bytes": output.stat().st_size},
                     sort_keys=True))


if __name__ == "__main__":
    main()
