/* Auto-generated by scripts/generate_badge_atlas.py.
 * Catalog content ID: b7dd198d295b955b
 */

#ifndef PES21_BADGE_ATLAS_H
#define PES21_BADGE_ATLAS_H

#include <stdint.h>

#define BADGE_ATLAS_CONTENT_ID "b7dd198d295b955b"
#define BADGE_CELL_SIZE 128
#define BADGE_ATLAS_COLS 32
#define BADGE_ATLAS_CATALOG_SLOTS 514
#define BADGE_ATLAS_SLOTS 514
#define BADGE_ATLAS_ROWS 17
#define BADGE_ATLAS_W (BADGE_CELL_SIZE * BADGE_ATLAS_COLS)
#define BADGE_ATLAS_H (BADGE_CELL_SIZE * BADGE_ATLAS_ROWS)
#define BADGE_ATLAS_BYTES (BADGE_ATLAS_W * BADGE_ATLAS_H * 4u)

/* data/badge_atlas.bin is converted to this symbol by the devkitPro build. */
extern const uint8_t badge_atlas_bin[];
#define badge_atlas_rgba8 badge_atlas_bin

#endif
