/* Generated by tools/build_fl26_league_catalog.py; do not edit. */
#ifndef PES21_FL26_LEAGUE_CATALOG_GENERATED_H
#define PES21_FL26_LEAGUE_CATALOG_GENERATED_H
#include <stdint.h>
typedef struct {
  uint16_t competition_id;
  uint8_t category_index;
  uint8_t default_team_count;
  const char *name;
  const char *logo_file;
  const uint32_t *team_ids;
  uint32_t pool_count;
} Fl26LeagueCatalogEntry;
static const uint32_t fl26_league_pool_0[] = {101u, 107u, 4071u, 4180u, 377u, 378u, 102u, 382u, 177u, 178u, 103u, 104u, 173u, 100u, 106u, 389u, 179u, 105u, 208u};
static const uint32_t fl26_league_pool_1[] = {234u, 186u, 320u, 4220u, 124u, 323u, 336u, 120u, 122u, 4237u, 119u, 121u, 327u, 123u, 4241u, 125u, 1919u, 333u, 190u};
static const uint32_t fl26_league_pool_2[] = {4145u, 258u, 108u, 194u, 361u, 259u, 362u, 2187u, 366u, 261u, 172u, 109u, 263u, 4260u, 265u, 196u, 110u, 370u, 195u, 267u};
static const uint32_t fl26_league_pool_3[] = {403u, 180u, 1329u, 413u, 182u, 213u, 414u, 4123u, 112u, 216u, 217u, 181u, 113u, 114u, 4211u, 218u, 4213u, 221u};
static const uint32_t fl26_league_pool_4[] = {116u, 242u, 117u, 345u, 244u, 245u, 349u, 118u, 351u, 250u, 251u, 256u};
static const uint32_t fl26_league_pool_5[] = {191u, 5028u, 2387u, 2388u, 1944u, 192u, 1979u, 2391u, 1974u, 193u, 2614u, 1804u};
static const uint32_t fl26_league_pool_6[] = {1245u, 2453u, 1246u, 2459u, 2454u, 1247u, 274u, 1248u, 1249u, 5143u, 1250u, 1252u, 5137u, 137u, 1254u, 1255u, 136u, 1937u};
static const uint32_t fl26_league_pool_7[] = {167u, 169u, 168u, 1881u, 157u, 146u, 149u, 163u, 156u, 2372u, 155u, 159u, 153u, 165u, 150u, 151u, 147u, 158u, 164u, 152u};
static const uint32_t fl26_league_pool_8[] = {5202u, 1989u, 273u, 5652u, 197u, 130u, 5356u, 1230u, 5203u, 1995u, 2625u, 1996u, 5204u, 5354u, 1945u};
static const uint32_t fl26_league_pool_9[] = {176u, 1760u, 201u, 203u, 4183u, 383u, 1589u, 204u, 205u, 387u, 388u, 4192u, 1327u, 4194u, 394u, 207u, 395u, 1909u, 398u, 399u};
static const uint32_t fl26_league_pool_10[] = {4302u, 357u, 4308u, 4395u, 111u, 4146u, 1765u, 363u, 2188u, 364u, 4272u, 260u, 2616u, 264u, 266u, 268u};
static const uint32_t fl26_league_pool_11[] = {4200u, 407u, 4206u, 4370u, 211u, 215u, 415u, 418u, 5099u, 1330u, 4372u, 420u};
static const Fl26LeagueCatalogEntry fl26_league_catalog[] = {
  {9u, 0u, 19u, "PREMIER LEAGUE", "emb_0009_l.png", fl26_league_pool_0, 19u},
  {10u, 6u, 19u, "SERIE A", "emb_0010_w_l.png", fl26_league_pool_1, 19u},
  {11u, 2u, 20u, "LA LIGA", "emb_0011_l.png", fl26_league_pool_2, 20u},
  {12u, 4u, 18u, "LIGUE 1", "emb_0012_w_l.png", fl26_league_pool_3, 18u},
  {13u, 8u, 12u, "EREDIVISIE", "emb_0013_w_l.png", fl26_league_pool_4, 12u},
  {14u, 9u, 12u, "LIGA PORTUGAL", "emb_0014_w_l.png", fl26_league_pool_5, 12u},
  {21u, 14u, 18u, "BRASILEIRAO SERIE A", "emb_0021_w_l.png", fl26_league_pool_6, 18u},
  {41u, 17u, 20u, "J1 LEAGUE", "emb_0041_w_l.png", fl26_league_pool_7, 20u},
  {119u, 11u, 15u, "TURKISH SUPER LIG", "emb_0119_w_l.png", fl26_league_pool_8, 15u},
  {66u, 1u, 20u, "ENGLISH CHAMPIONSHIP", "emb_0066_l.png", fl26_league_pool_9, 20u},
  {67u, 3u, 16u, "SPANISH 2ND DIV", "emb_0067_l.png", fl26_league_pool_10, 16u},
  {68u, 5u, 12u, "LIGUE 2", "emb_0068_w_l.png", fl26_league_pool_11, 12u},
  {0u, 255u, 16u, "FOOTBALLNX LEAGUE", 0, 0, 0u},
};
#define FL26_LEAGUE_CUSTOM_INDEX 12u
#define FL26_LEAGUE_CATALOG_COUNT ((uint32_t)(sizeof(fl26_league_catalog) / sizeof(fl26_league_catalog[0])))
#endif
