#pragma once

#include <stdint.h>
extern const uint8_t main_menu_button_a_bin[];
extern const uint8_t main_menu_button_a_bin_end[];

/* PNG payloads generated by tools/build_main_menu_assets.py and bin2o. */
extern const uint8_t main_menu_background_bin[];
extern const uint8_t main_menu_background_bin_end[];
extern const uint8_t main_menu_icons_bin[];
extern const uint8_t main_menu_icons_bin_end[];
extern const uint8_t main_menu_brand_bin[];
extern const uint8_t main_menu_brand_bin_end[];
extern const uint8_t main_menu_portrait_exhibition_bin[];
extern const uint8_t main_menu_portrait_exhibition_bin_end[];
extern const uint8_t main_menu_portrait_2player_bin[];
extern const uint8_t main_menu_portrait_2player_bin_end[];
extern const uint8_t main_menu_portrait_settings_bin[];
extern const uint8_t main_menu_portrait_settings_bin_end[];
extern const uint8_t main_menu_portrait_credits_bin[];
extern const uint8_t main_menu_portrait_credits_bin_end[];
