#ifndef PES_STADIUM_LITE_GLSL_H
#define PES_STADIUM_LITE_GLSL_H

/* Authored analytic roof proxy, in UE centimetres. It is shared by pitch,
 * bodies and faces: moving receivers intersect the same elevated plane.
 * No native roof mesh, depth atlas, texture binding or extra draw is needed.
 * Keep helpers as separate strings so host tests can execute the exact math. */
static const char stadium_lite_geometry_glsl[] =
  "highp float nxRoofDistance(highp vec2 p, highp vec2 extent, highp float radius) {\n"
  "  highp vec2 q=abs(p)-extent+vec2(radius);\n"
  "  return length(max(q,vec2(0.0)))+min(max(q.x,q.y),0.0)-radius;\n"
  "}\n"
  "highp float nxRoofProxy(highp vec2 p, highp float edge) {\n"
  "  highp float inner=nxRoofDistance(p,vec2(5700.0,3700.0),1400.0);\n"
  "  highp float outer=nxRoofDistance(p,vec2(7800.0,5800.0),2000.0);\n"
  "  highp float roof=smoothstep(-edge,edge,inner)*(1.0-smoothstep(-edge,edge,outer));\n"
  "  highp float slot1=smoothstep(260.0-edge,260.0+edge,inner)*(1.0-smoothstep(620.0-edge,620.0+edge,inner));\n"
  "  highp float slot2=smoothstep(1050.0-edge,1050.0+edge,inner)*(1.0-smoothstep(1360.0-edge,1360.0+edge,inner));\n"
  "  highp vec2 side=abs(p)-vec2(4300.0,2300.0);\n"
  "  highp float along=(side.x>side.y)?p.y:p.x;\n"
  "  highp float beam=abs(fract(along/650.0+0.5)-0.5)*650.0;\n"
  "  highp float opening=max(slot1,slot2)*smoothstep(24.0-edge,24.0+edge,beam);\n"
  "  return 1.0-roof*(1.0-opening);\n"
  "}\n"
  "highp vec2 nxRoofProject(highp vec3 world,highp vec3 light) {\n"
  "  return world.xy+light.xy*((3600.0-world.z)/max(light.z,0.2));\n"
  "}\n";

static const char stadium_lite_helpers_glsl[] =
  "uniform highp float nxNightIndirect;\n"
  "uniform highp float nxDayStadium;\n"
  "uniform highp vec4 nxStadiumClimate;\n"
  "uniform highp float nxStadiumProfile;\n"
  "highp vec3 nxNeutralLight(highp vec3 light) {\n"
  "  if(nxNightIndirect>0.5 || nxDayStadium>0.5)\n"
  "    return vec3(dot(max(light,vec3(0.0)),vec3(0.2126,0.7152,0.0722)));\n"
  "  return light;\n"
  "}\n"
  "highp float nxRoofVisibility(highp vec3 world) {\n"
  "  highp vec3 sun=MobileDirectionalLight_DirectionalLightDirectionAndShadowTransition.xyz;\n"
  "  highp float season=1.0+0.45*nxStadiumClimate.y;\n"
  "  highp vec2 p=nxRoofProject(world,vec3(sun.x*season,sun.y*season,sun.z));\n"
  "  highp float edge=clamp(max(fwidth(p.x),fwidth(p.y))*0.75,8.0,70.0)+50.0*min(nxStadiumClimate.x,1.0);\n"
  "  if(nxStadiumProfile>0.5) {\n"
  "    p=nxRoofProject(vec3(world.x,world.y,world.z+600.0),vec3(sun.x*season,sun.y*season,sun.z));\n"
  "    highp float inner=nxRoofDistance(p,vec2(5650.0,4200.0),150.0);\n"
  "    highp float outer=nxRoofDistance(p,vec2(11000.0,8500.0),250.0);\n"
  "    highp float visible=1.0-smoothstep(-edge,edge,inner)*(1.0-smoothstep(-edge,edge,outer));\n"
  "    return mix(visible,1.0,0.65*min(nxStadiumClimate.x,1.0));\n"
  "  }\n"
  "  return mix(nxRoofProxy(p,edge),1.0,0.65*min(nxStadiumClimate.x,1.0));\n"
  "}\n"
  "highp vec3 nxSeasonLight() {\n"
  "  highp float winter=nxDayStadium>0.5 ? nxStadiumClimate.y : 0.0;\n"
  "  return vec3(1.0-0.07*winter,1.0-0.025*winter,1.0+0.05*winter);\n"
  "}\n"
  "highp vec3 nxRainLightScale() {\n"
  "  if(nxStadiumClimate.x<1.5) return vec3(1.0);\n"
  "  highp vec3 cool=nxDayStadium>0.5 ? vec3(1.0) : vec3(0.97,1.02,1.07);\n"
  "  return mix(vec3(0.84),cool,nxStadiumClimate.y);\n"
  "}\n"
  "highp float nxCloudLight() {\n"
  "  if(nxDayStadium<0.5) return 0.0;\n"
  "  highp float cloud=min(nxStadiumClimate.x,1.0);\n"
  "  if(nxStadiumClimate.x>1.5) cloud*=1.0-0.92*nxStadiumClimate.y;\n"
  "  return cloud;\n"
  "}\n"
  "highp vec3 nxDirectLight(highp vec3 light,highp float visibility) {\n"
  "  return nxNeutralLight(light)*nxSeasonLight()*nxRainLightScale()*mix(1.0,0.62,nxCloudLight())*mix(0.12,1.0,visibility);\n"
  "}\n"
  "highp vec3 nxAmbientLight(highp vec3 light,highp float visibility) {\n"
  "  return nxNeutralLight(light)*nxSeasonLight()*nxRainLightScale()*mix(1.0,1.10,nxCloudLight())*mix(0.56,1.0,visibility);\n"
  "}\n"
  "highp float nxWeatherHash(highp vec2 p) {\n"
  "  p=fract(p*vec2(0.1031,0.11369));\n"
  "  highp float h=dot(p,p+vec2(19.19));\n"
  "  return fract((p.x+h)*(p.y+h));\n"
  "}\n"
  "highp float nxWeatherNoise(highp vec2 p) {\n"
  "  highp vec2 i=floor(p), f=fract(p);\n"
  "  f=f*f*(vec2(3.0)-f*2.0);\n"
  "  return mix(mix(nxWeatherHash(i),nxWeatherHash(i+vec2(1.0,0.0)),f.x),\n"
  "             mix(nxWeatherHash(i+vec2(0.0,1.0)),nxWeatherHash(i+vec2(1.0)),f.x),f.y);\n"
  "}\n"
  "highp vec2 nxWeatherCoverage(highp vec3 world) {\n"
  "  highp vec2 p=world.xy*0.0016;\n"
  "  highp float broad=nxWeatherNoise(p);\n"
  "  highp float broken=nxWeatherNoise(p*3.17+vec2(27.3,9.1));\n"
  "  highp float fleck=broken; // reuse detail; no third noise octave\n"
  "  highp float wet=smoothstep(0.36,0.76,broad*0.72+broken*0.28);\n"
  "  highp float snow=smoothstep(0.57,0.79,broad*0.64+broken*0.36)*mix(0.30,1.0,fleck);\n"
  "  return vec2(wet,snow);\n"
  "}\n"
  "highp vec3 nxPitchWeather(highp vec3 color,highp vec3 world) {\n"
  "  if(nxStadiumClimate.x<1.5) return color;\n"
  "  // Only audited pitch materials; preserve white paint and out-of-field edges.\n"
  "  if(abs(world.x)>5400.0 || abs(world.y)>3550.0 || abs(world.z)>100.0 ||\n"
  "     color.g<color.r*1.07 || color.g<color.b*1.12) return color;\n"
  "  highp vec2 cover=nxWeatherCoverage(world);\n"
  "  highp float winter=nxStadiumClimate.y;\n"
  "  highp vec3 wet=color*mix(0.91-cover.x*0.40,0.99-cover.x*0.14,winter);\n"
  "  // Thin remnants retain grass/stripes; no luminous solid snow blanket.\n"
  "  highp float snowLight=clamp(color.g*1.8,0.16,0.65);\n"
  "  return mix(wet,vec3(0.91,0.95,1.0)*snowLight,cover.y*0.82*winter);\n"
  "}\n"
  "highp vec3 nxPitchGrain(highp vec3 albedo,highp float grain) {\n"
  "  if(nxDayStadium>0.5 && albedo.g>albedo.r*1.14 && albedo.g>albedo.b*1.3) {\n"
  "    highp float contrast=clamp(1.0+(albedo.g-0.09)*5.0,0.85,1.16);\n"
  "    highp float detail=0.16+0.055*nxStadiumClimate.z;\n"
  "    highp float wet=nxStadiumClimate.w;\n"
  "    highp float damp=1.0-wet*(wet<0.0 ? 0.025 : 0.08);\n"
  "    return (albedo*vec3(0.58,1.12,0.46))*(contrast*damp*mix(1.0-detail,1.0+detail,clamp(grain,0.0,1.0)));\n"
  "  }\n"
  "  return albedo;\n"
  "}\n"
  "highp vec3 nxPitchSheen(highp vec3 light,highp float visibility) {\n"
  "  highp float wet=nxStadiumClimate.w;\n"
  "  if(nxDayStadium>0.5) return nxNeutralLight(light)*((0.025+wet*(wet<0.0 ? 0.015 : 0.065))*visibility);\n"
  "  return light;\n"
  "}\n";
#endif
